### ISSUE TITLE
Doesn't work in iOS 5 Beta

### ISSUE THREAD

**Issue by smfr** [joehewitt/scrollability#11]
In iOS 5 beta (and Safari 5.1 on desktop) -webkit-transform is taken into account for overflow, so will now cause the creation of overflow scrollbars, and will affect scrollHeight. This breaks Scrollability.

**Comment by revolunet** [comment]
doesnt scrollability be disabled for IOS5 as overflow:scroll works there natively ?

more info here : http://johanbrook.com/browsers/native-momentum-scrolling-ios-5/

**Comment by cheeaun** [comment]
@revolunet Even though it works natively in iOS5, it has scrollbars, momentum and zoom disabled for the scrolling div/element. More info: http://cubiq.org/what-you-can-really-do-with-native-position-fixed

**Comment by aronwoost** [comment]
+1 @cheeaun. We still need scrollability.

**Comment by focalstrategy** [comment]
Not anymore, apparently you can use 

overflow: scroll;
-webkit-overflow-scrolling: touch;

to have the same effect.

**Comment by gojosh** [comment]
Aside from the need for a fallback, I still prefer a CSS transform-based scroller. Currently in iOS5 beta 2, my CSS transitions are paused during touch overflow scrolling. This causes various problems. As an example, I've implemented a simulation of the UITableView row "tapped" blue fadeout using CSS transitions. When scrolling, the overflow-scrolling:touch div freezes the otherwise canceled highlight in its bright blue state.

**Comment by smfr** [comment]
Did you mean "CSS transitions are paused during touch overflow scrolling"?

**Comment by gojosh** [comment]
Sorry -- yes -- transitions. I chronically conflate those terms. Fixed.

**Comment by joehewitt** [comment]
Works in iOS 5 as of latest rewrite.
